server:
  port: 8080
spring:
  application:
    name: "nequi-franchise"
  profiles:
    active: ${FRANCHISE_PROFILE_ACTIVE}
  flyway:
    url: 'jdbc:postgresql://${FRANCHISE_R2DBC_HOST}:${FRANCHISE_R2DBC_PORT}/${FRANCHISE_R2DBC_DATABASE}'
    user: '${FRANCHISE_R2DBC_USERNAME}'
    password: '${FRANCHISE_R2DBC_PASSWORD}'
    enabled: true
    locations: 'classpath:db/migration'
    baseline-on-migrate: true
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: '${spring.application.name}'

cors:
  allowed-origins: '${CORS_ALLOWED_ORIGINS}'

adapters:
  r2dbc:
    host: '${FRANCHISE_R2DBC_HOST}'
    port: '${FRANCHISE_R2DBC_PORT}'
    database: '${FRANCHISE_R2DBC_DATABASE}'
    schema: '${FRANCHISE_R2DBC_SCHEMA}'
    username: '${FRANCHISE_R2DBC_USERNAME}'
    password: '${FRANCHISE_R2DBC_PASSWORD}'

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    co.com.franchise: DEBUG
    org.springframework.r2dbc: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.franchise: INFO
